const url = "http://localhost:8081";
describe("Sports Specialist", () => {
  it("sports specialist list is not empty", () => {
    cy.viewport(390, 844);
    cy.visit(url);
    cy.wait(500);
    cy.contains("Empezar").click();
    cy.wait(500);
    cy.get("[placeholder=Correo]").type("dani@hotmail.com");
    cy.wait(500);
    cy.get("[placeholder=Contraseña]").type("Messi96*");
    cy.wait(500);
    cy.contains("Iniciar sesión").click();
    cy.wait(2000);
    cy.contains("Servicios").click();
    cy.wait(1000);
    cy.contains("Deportologo").click();
    cy.wait(1000);
    cy.contains("26").click();
    cy.wait(500);
    cy.contains("Ver disponibilidad").click();
    cy.wait(2000);
  });

  it("sports specialists list is empty", () => {
    cy.viewport(390, 844);
    cy.visit(url);
    cy.wait(500);
    cy.contains("Empezar").click();
    cy.wait(500);
    cy.get("[placeholder=Correo]").type("dani@hotmail.com");
    cy.wait(500);
    cy.get("[placeholder=Contraseña]").type("Messi96*");
    cy.wait(500);
    cy.contains("Iniciar sesión").click();
    cy.wait(2000);
    cy.contains("Servicios").click();
    cy.wait(1000);
    cy.contains("Deportologo").click();
    cy.wait(1000);
    cy.contains("22").click();
    cy.wait(500);
    cy.contains("Ver disponibilidad").click();
    cy.wait(2000);
  });
  it("no date selected", () => {
    cy.viewport(390, 844);
    cy.visit(url);
    cy.wait(500);
    cy.contains("Empezar").click();
    cy.wait(500);
    cy.get("[placeholder=Correo]").type("dani@hotmail.com");
    cy.wait(500);
    cy.get("[placeholder=Contraseña]").type("Messi96*");
    cy.wait(500);
    cy.contains("Iniciar sesión").click();
    cy.wait(2000);
    cy.contains("Servicios").click();
    cy.wait(1000);
    cy.contains("Deportologo").click();
    cy.wait(1000);
  });
  it("sports specialist detail", () => {
    cy.viewport(390, 844);
    cy.visit(url);
    cy.wait(500);
    cy.contains("Empezar").click();
    cy.wait(500);
    cy.get("[placeholder=Correo]").type("dani@hotmail.com");
    cy.wait(500);
    cy.get("[placeholder=Contraseña]").type("Messi96*");
    cy.wait(500);
    cy.contains("Iniciar sesión").click();
    cy.wait(2000);
    cy.contains("Servicios").click();
    cy.wait(1000);
    cy.contains("Deportologo").click();
    cy.wait(1000);
    cy.contains("26").click();
    cy.wait(500);
    cy.contains("Ver disponibilidad").click();
    cy.wait(2000);
    cy.get("[aria-label=specialist]").should("exist").first().click();
    cy.wait(1500);
  });
  it("sports specialist reservation successful", () => {
    cy.viewport(390, 844);
    cy.visit(url);
    cy.wait(500);
    cy.contains("Empezar").click();
    cy.wait(500);
    cy.get("[placeholder=Correo]").type("dani@hotmail.com");
    cy.wait(500);
    cy.get("[placeholder=Contraseña]").type("Messi96*");
    cy.wait(500);
    cy.contains("Iniciar sesión").click();
    cy.wait(2000);
    cy.contains("Servicios").click();
    cy.wait(1000);
    cy.contains("Deportologo").click();
    cy.wait(1000);
    cy.contains("26").click();
    cy.wait(500);
    cy.contains("Ver disponibilidad").click();
    cy.wait(2000);
    cy.get("[aria-label=specialist]").should("exist").first().click();
    cy.wait(1500);
    cy.contains("Reservar").click();
    cy.wait(2000);
  });
});
